# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 240)
        Dialog.setSizeIncrement(QtCore.QSize(320, 240))
        Dialog.setBaseSize(QtCore.QSize(320, 240))
        Dialog.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(6, -1, 6, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.imieLabel = QtWidgets.QLabel(Dialog)
        self.imieLabel.setObjectName("imieLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.imieLabel)
        self.labelImie = QtWidgets.QLabel(Dialog)
        self.labelImie.setText("")
        self.labelImie.setScaledContents(False)
        self.labelImie.setObjectName("labelImie")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelImie)
        self.nazwiskoLabel = QtWidgets.QLabel(Dialog)
        self.nazwiskoLabel.setObjectName("nazwiskoLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nazwiskoLabel)
        self.labelNazwisko = QtWidgets.QLabel(Dialog)
        self.labelNazwisko.setText("")
        self.labelNazwisko.setObjectName("labelNazwisko")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelNazwisko)
        self.dataLabel = QtWidgets.QLabel(Dialog)
        self.dataLabel.setObjectName("dataLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dataLabel)
        self.labelData = QtWidgets.QLabel(Dialog)
        self.labelData.setText("")
        self.labelData.setObjectName("labelData")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelData)
        self.nartyLabel = QtWidgets.QLabel(Dialog)
        self.nartyLabel.setObjectName("nartyLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.nartyLabel)
        self.labelNarty = QtWidgets.QLabel(Dialog)
        self.labelNarty.setText("")
        self.labelNarty.setObjectName("labelNarty")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelNarty)
        self.snowboardLabel = QtWidgets.QLabel(Dialog)
        self.snowboardLabel.setObjectName("snowboardLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.snowboardLabel)
        self.labelSnowboard = QtWidgets.QLabel(Dialog)
        self.labelSnowboard.setText("")
        self.labelSnowboard.setObjectName("labelSnowboard")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelSnowboard)
        self.butyLabel = QtWidgets.QLabel(Dialog)
        self.butyLabel.setObjectName("butyLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.butyLabel)
        self.labelButy = QtWidgets.QLabel(Dialog)
        self.labelButy.setText("")
        self.labelButy.setObjectName("labelButy")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.labelButy)
        self.kaskLabel = QtWidgets.QLabel(Dialog)
        self.kaskLabel.setObjectName("kaskLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.kaskLabel)
        self.labelKask = QtWidgets.QLabel(Dialog)
        self.labelKask.setText("")
        self.labelKask.setObjectName("labelKask")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.labelKask)
        self.kijkiLabel = QtWidgets.QLabel(Dialog)
        self.kijkiLabel.setObjectName("kijkiLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.kijkiLabel)
        self.labelKijki = QtWidgets.QLabel(Dialog)
        self.labelKijki.setText("")
        self.labelKijki.setObjectName("labelKijki")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.labelKijki)
        self.rozliczonyLabel = QtWidgets.QLabel(Dialog)
        self.rozliczonyLabel.setObjectName("rozliczonyLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.rozliczonyLabel)
        self.labelRozliczony = QtWidgets.QLabel(Dialog)
        self.labelRozliczony.setText("")
        self.labelRozliczony.setObjectName("labelRozliczony")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.labelRozliczony)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pokaż"))
        self.imieLabel.setText(_translate("Dialog", "Imie:"))
        self.nazwiskoLabel.setText(_translate("Dialog", "Nazwisko:"))
        self.dataLabel.setText(_translate("Dialog", "Data wypożyczenia:"))
        self.nartyLabel.setText(_translate("Dialog", "Narty: "))
        self.snowboardLabel.setText(_translate("Dialog", "Snowboard:"))
        self.butyLabel.setText(_translate("Dialog", "Buty:"))
        self.kaskLabel.setText(_translate("Dialog", "Kask:"))
        self.kijkiLabel.setText(_translate("Dialog", "Kijki:"))
        self.rozliczonyLabel.setText(_translate("Dialog", "Rozliczony:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
